import type { Character } from '../model/types';

export function getCharacters(t: (key: string) => string): Character[] {
  // Centralize character construction; strings come from i18n via t()
  return [
    {
      id: 'characterSinger',
      name: 'Singer Faksumi',
      age: 17,
      information: t('singerDescription'),
      profile: '/CharacterSection/profile/Singer Profile.png',
      withoutText: '/CharacterSection/withoutText/Singer withoutText.png',
      withText: '/CharacterSection/withText/Singer corpo completo.png',
      colorTheme: 'lightblue',
      appeared: true,
      height: 'lg:h-[100%]',
    },
    {
      id: 'characterAika',
      name: "Aika'nu Zumiki",
      age: 19,
      information: t('noRegister'),
      profile: '/CharacterSection/profile/Aika Profile.png',
      withoutText: '/CharacterSection/withoutText/Aika withoutText.png',
      withText: '/CharacterSection/withText/Aika corpo completo.png',
      colorTheme: 'rgb(255, 223, 239)',
      appeared: false,
      height: 'lg:h-[95%]',
    },
    {
      id: 'characterMadger',
      name: 'Madger Yasáshi',
      age: 17,
      information: t('madgerDescription'),
      profile: '/CharacterSection/profile/Madger Profile.png',
      withoutText: '/CharacterSection/withoutText/Madger withoutText.png',
      withText: '/CharacterSection/withText/Madger corpo completo.png',
      colorTheme: 'rgb(186, 235, 186)',
      appeared: true,
      height: 'lg:h-[95%]',
    },
    {
      id: 'characterSan',
      name: 'San Majutsu-shi',
      age: 19,
      information: t('noRegister'),
      profile: '/CharacterSection/profile/San Profile.png',
      withoutText: '/CharacterSection/withoutText/San withoutText.png',
      withText: '/CharacterSection/withText/San corpo completo.png',
      colorTheme: 'rgb(255, 223, 164)',
      appeared: false,
      height: 'lg:h-[99%]',
    },
    {
      id: 'characterMálanus',
      name: 'Málanus Faksumi',
      age: 25,
      information: t('málanusDescription'),
      profile: '/CharacterSection/profile/Málanus Profile.png',
      withoutText: '/CharacterSection/withoutText/Málanus withoutText.png',
      withText: '/CharacterSection/withText/Málanus corpo completo.png',
      colorTheme: 'rgb(255, 164, 164)',
      appeared: true,
      height: 'lg:h-[100%]',
    },
    {
      id: 'characterKaononai',
      name: 'Kaononai',
      age: '??',
      information: t('kaononaiDescription'),
      profile: '/CharacterSection/profile/Kaononai Profile.png',
      withoutText: '/CharacterSection/withoutText/Kaononai withoutText.png',
      withText: '/CharacterSection/withText/Kaononai corpo completo.png',
      colorTheme: 'rgb(255 222 91)',
      appeared: true,
      height: 'lg:h-[102%]',
    },
  ];
}
